on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: palloregistry.azurecr.io
        username: ${{ secrets.acr_palloregistry_username }}
        password: ${{ secrets.acr_palloregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "./Dockerfile" -t palloregistry.azurecr.io/pallok8s:${{ github.sha }} --label dockerfile-path=.
        docker push palloregistry.azurecr.io/pallok8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_pallok8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep comingsoon | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace comingsoon`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: comingsoon
        container-registry-url: palloregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_palloregistry_username }}
        container-registry-password: ${{ secrets.acr_palloregistry_password }}
        secret-name: pallok8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: comingsoon
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          palloregistry.azurecr.io/pallok8s:${{ github.sha }}
        imagepullsecrets: |
          pallok8sdockerauth
