on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: palloregistry.azurecr.io
        username: ${{ secrets.acr_palloregistry_username }}
        password: ${{ secrets.acr_palloregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t palloregistry.azurecr.io/k8s:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push palloregistry.azurecr.io/k8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demo | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demo`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demo
        container-registry-url: palloregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_palloregistry_username }}
        container-registry-password: ${{ secrets.acr_palloregistry_password }}
        secret-name: k8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: demo
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          palloregistry.azurecr.io/k8s:${{ github.sha }}
        imagepullsecrets: |
          k8sdockerauth
